-- Data migration for the canonical-Card + CardPrinting refactor.
-- Rules-equivalence dedup: only true reprints/alt-arts (identical rules)
-- merge; genuinely-different same-named cards stay separate.
-- GENERATED by gen_migration.py from a prod dump. Run AFTER 01_schema.sql,
-- on a DB snapshot first. Transaction-wrapped; safe to re-run on the same DB.

START TRANSACTION;

-- 1) One printing per existing card (idempotent via NOT EXISTS).
INSERT INTO card_printing
    (card_id, pack_id, position, quantity, image_code, illustrator, octgnid, date_creation, date_update)
  SELECT c.id, c.pack_id, c.position, c.quantity, c.code, c.illustrator, c.octgnid, c.date_creation, c.date_update
  FROM card c
  WHERE NOT EXISTS (SELECT 1 FROM card_printing cp WHERE cp.card_id = c.id AND cp.pack_id = c.pack_id);

-- 2) Merge map: losing card id -> canonical (earliest) card id.
CREATE TEMPORARY TABLE _merge_map (loser_id INT PRIMARY KEY, canonical_id INT NOT NULL);
INSERT INTO _merge_map (loser_id, canonical_id) VALUES
  (757,950),
  (758,1067),
  (824,1),
  (825,452),
  (826,73),
  (827,514),
  (828,525),
  (829,14),
  (830,162),
  (831,342),
  (832,142),
  (833,455),
  (834,456),
  (835,17),
  (836,329),
  (837,636),
  (838,597),
  (839,301),
  (840,305),
  (841,593),
  (842,27),
  (843,26),
  (844,183),
  (845,57),
  (846,100),
  (847,460),
  (848,25),
  (849,23),
  (850,50),
  (851,20),
  (852,48),
  (853,587),
  (854,53),
  (855,312),
  (856,11),
  (857,125),
  (858,73),
  (859,526),
  (860,101),
  (861,516),
  (862,552),
  (863,540),
  (864,60),
  (865,610),
  (866,364),
  (867,59),
  (868,333),
  (869,327),
  (870,203),
  (871,682),
  (872,214),
  (873,42),
  (874,510),
  (875,130),
  (876,39),
  (877,328),
  (878,422),
  (879,112),
  (880,34),
  (881,66),
  (882,35),
  (883,135),
  (884,131),
  (885,184),
  (886,324),
  (1277,275),
  (1278,453),
  (1279,125),
  (1280,154),
  (1281,458),
  (1282,59),
  (1283,134),
  (1284,579),
  (1285,272),
  (1286,73),
  (1287,477),
  (1288,178),
  (1289,61),
  (1290,460),
  (1291,185),
  (1292,489),
  (1293,165),
  (1294,126),
  (1295,462),
  (1296,463),
  (1297,274),
  (1298,149),
  (1299,188),
  (1300,127),
  (1301,452),
  (1302,456),
  (1303,455),
  (1304,132),
  (1305,625),
  (1306,641),
  (1307,730),
  (1308,300),
  (1309,340),
  (1310,320),
  (1311,329),
  (1312,327),
  (1313,345),
  (1314,73),
  (1315,624),
  (1316,60),
  (1317,282),
  (1318,301),
  (1319,342),
  (1320,230),
  (1321,121),
  (1322,328),
  (1323,349),
  (1324,322),
  (1325,338),
  (1326,50),
  (1327,184),
  (1328,163),
  (1329,312),
  (1330,970),
  (1331,308),
  (1332,333),
  (1333,313),
  (1334,334),
  (1335,190),
  (1336,324),
  (1337,196),
  (1338,187),
  (1339,198),
  (1340,94),
  (1341,330),
  (1342,962),
  (1343,951),
  (1344,200),
  (1345,203),
  (1346,266),
  (1347,199),
  (1348,14),
  (1349,73),
  (1350,29),
  (1351,214),
  (1352,256),
  (1353,353),
  (1354,219),
  (1355,341),
  (1356,26),
  (1357,1069),
  (1358,267),
  (1359,204),
  (1360,34),
  (1361,963),
  (1362,952),
  (1363,24),
  (1364,464),
  (1365,197),
  (1366,245),
  (1367,724),
  (1368,213),
  (1369,243),
  (1370,643),
  (1371,1076),
  (1372,179),
  (1373,285),
  (1374,675),
  (1375,961),
  (1376,89),
  (1377,99),
  (1378,73),
  (1379,258),
  (1380,30),
  (1381,711),
  (1382,280),
  (1383,79),
  (1384,291),
  (1385,1094),
  (1386,290),
  (1387,100),
  (1388,303),
  (1389,969),
  (1390,678),
  (1391,966),
  (1392,50),
  (1393,281),
  (1394,34),
  (1395,269),
  (1396,689),
  (1397,980),
  (1398,639),
  (1399,685),
  (1400,109),
  (1401,268),
  (1402,270),
  (1403,292),
  (1404,344),
  (1457,177),
  (1458,938),
  (1459,907),
  (1460,104),
  (1583,454),
  (1631,340),
  (1632,549);

-- 3) Repoint the losers' printings onto the canonical card. (Merged cards share
--    the same rules, so printings carry only art differences -- no rules overrides.)
UPDATE card_printing cp JOIN _merge_map m ON cp.card_id = m.loser_id SET cp.card_id = m.canonical_id;

-- 4) Repoint every saved reference (FKs to card.id).
UPDATE deckslot s JOIN _merge_map m ON s.card_id = m.loser_id SET s.card_id = m.canonical_id;
UPDATE decklistslot s JOIN _merge_map m ON s.card_id = m.loser_id SET s.card_id = m.canonical_id;
UPDATE decksideslot s JOIN _merge_map m ON s.card_id = m.loser_id SET s.card_id = m.canonical_id;
UPDATE decklistsideslot s JOIN _merge_map m ON s.card_id = m.loser_id SET s.card_id = m.canonical_id;
UPDATE review s JOIN _merge_map m ON s.card_id = m.loser_id SET s.card_id = m.canonical_id;

-- NOTE: deck-edit history (deckchange.variation) stores card CODES in JSON and is
--   intentionally NOT rewritten -- loser codes become unresolved in the history
--   view only (deck CONTENTS via *_slot are repointed above and stay correct).

-- 5) Collapse duplicate printings now sharing the same canonical card AND pack
--    (e.g. a card printed twice in one pack): keep one, sum quantity.
UPDATE card_printing cp JOIN (
    SELECT MIN(id) keep_id, SUM(quantity) tq FROM card_printing
    GROUP BY card_id, pack_id HAVING COUNT(*) > 1
  ) d ON cp.id = d.keep_id SET cp.quantity = d.tq;
DELETE cp FROM card_printing cp JOIN (
    SELECT card_id, pack_id, MIN(id) keep_id FROM card_printing
    GROUP BY card_id, pack_id HAVING COUNT(*) > 1
  ) d ON cp.card_id = d.card_id AND cp.pack_id = d.pack_id AND cp.id <> d.keep_id;

-- 6) Dedup any slot that now has two rows for the same canonical card (sum qty).
UPDATE deckslot s JOIN (
    SELECT MIN(id) keep_id, SUM(quantity) tq FROM deckslot
    WHERE card_id IN (1,11,14,17,20,23,24,25,26,27,29,30,34,35,39,42,48,50,53,57,59,60,61,66,73,79,89,94,99,100,101,104,109,112,121,125,126,127,130,131,132,134,135,142,149,154,162,163,165,177,178,179,183,184,185,187,188,190,196,197,198,199,200,203,204,213,214,219,230,243,245,256,258,266,267,268,269,270,272,274,275,280,281,282,285,290,291,292,300,301,303,305,308,312,313,320,322,324,327,328,329,330,333,334,338,340,341,342,344,345,349,353,364,422,452,453,454,455,456,458,460,462,463,464,477,489,510,514,516,525,526,540,549,552,579,587,593,597,610,624,625,636,639,641,643,675,678,682,685,689,711,724,730,907,938,950,951,952,961,962,963,966,969,970,980,1067,1069,1076,1094) GROUP BY deck_id, card_id HAVING COUNT(*) > 1
  ) d ON s.id = d.keep_id SET s.quantity = d.tq;
DELETE s FROM deckslot s JOIN (
    SELECT deck_id AS cont, card_id, MIN(id) keep_id FROM deckslot
    WHERE card_id IN (1,11,14,17,20,23,24,25,26,27,29,30,34,35,39,42,48,50,53,57,59,60,61,66,73,79,89,94,99,100,101,104,109,112,121,125,126,127,130,131,132,134,135,142,149,154,162,163,165,177,178,179,183,184,185,187,188,190,196,197,198,199,200,203,204,213,214,219,230,243,245,256,258,266,267,268,269,270,272,274,275,280,281,282,285,290,291,292,300,301,303,305,308,312,313,320,322,324,327,328,329,330,333,334,338,340,341,342,344,345,349,353,364,422,452,453,454,455,456,458,460,462,463,464,477,489,510,514,516,525,526,540,549,552,579,587,593,597,610,624,625,636,639,641,643,675,678,682,685,689,711,724,730,907,938,950,951,952,961,962,963,966,969,970,980,1067,1069,1076,1094) GROUP BY deck_id, card_id HAVING COUNT(*) > 1
  ) d ON s.deck_id = d.cont AND s.card_id = d.card_id AND s.id <> d.keep_id;
UPDATE decklistslot s JOIN (
    SELECT MIN(id) keep_id, SUM(quantity) tq FROM decklistslot
    WHERE card_id IN (1,11,14,17,20,23,24,25,26,27,29,30,34,35,39,42,48,50,53,57,59,60,61,66,73,79,89,94,99,100,101,104,109,112,121,125,126,127,130,131,132,134,135,142,149,154,162,163,165,177,178,179,183,184,185,187,188,190,196,197,198,199,200,203,204,213,214,219,230,243,245,256,258,266,267,268,269,270,272,274,275,280,281,282,285,290,291,292,300,301,303,305,308,312,313,320,322,324,327,328,329,330,333,334,338,340,341,342,344,345,349,353,364,422,452,453,454,455,456,458,460,462,463,464,477,489,510,514,516,525,526,540,549,552,579,587,593,597,610,624,625,636,639,641,643,675,678,682,685,689,711,724,730,907,938,950,951,952,961,962,963,966,969,970,980,1067,1069,1076,1094) GROUP BY decklist_id, card_id HAVING COUNT(*) > 1
  ) d ON s.id = d.keep_id SET s.quantity = d.tq;
DELETE s FROM decklistslot s JOIN (
    SELECT decklist_id AS cont, card_id, MIN(id) keep_id FROM decklistslot
    WHERE card_id IN (1,11,14,17,20,23,24,25,26,27,29,30,34,35,39,42,48,50,53,57,59,60,61,66,73,79,89,94,99,100,101,104,109,112,121,125,126,127,130,131,132,134,135,142,149,154,162,163,165,177,178,179,183,184,185,187,188,190,196,197,198,199,200,203,204,213,214,219,230,243,245,256,258,266,267,268,269,270,272,274,275,280,281,282,285,290,291,292,300,301,303,305,308,312,313,320,322,324,327,328,329,330,333,334,338,340,341,342,344,345,349,353,364,422,452,453,454,455,456,458,460,462,463,464,477,489,510,514,516,525,526,540,549,552,579,587,593,597,610,624,625,636,639,641,643,675,678,682,685,689,711,724,730,907,938,950,951,952,961,962,963,966,969,970,980,1067,1069,1076,1094) GROUP BY decklist_id, card_id HAVING COUNT(*) > 1
  ) d ON s.decklist_id = d.cont AND s.card_id = d.card_id AND s.id <> d.keep_id;
UPDATE decksideslot s JOIN (
    SELECT MIN(id) keep_id, SUM(quantity) tq FROM decksideslot
    WHERE card_id IN (1,11,14,17,20,23,24,25,26,27,29,30,34,35,39,42,48,50,53,57,59,60,61,66,73,79,89,94,99,100,101,104,109,112,121,125,126,127,130,131,132,134,135,142,149,154,162,163,165,177,178,179,183,184,185,187,188,190,196,197,198,199,200,203,204,213,214,219,230,243,245,256,258,266,267,268,269,270,272,274,275,280,281,282,285,290,291,292,300,301,303,305,308,312,313,320,322,324,327,328,329,330,333,334,338,340,341,342,344,345,349,353,364,422,452,453,454,455,456,458,460,462,463,464,477,489,510,514,516,525,526,540,549,552,579,587,593,597,610,624,625,636,639,641,643,675,678,682,685,689,711,724,730,907,938,950,951,952,961,962,963,966,969,970,980,1067,1069,1076,1094) GROUP BY deck_id, card_id HAVING COUNT(*) > 1
  ) d ON s.id = d.keep_id SET s.quantity = d.tq;
DELETE s FROM decksideslot s JOIN (
    SELECT deck_id AS cont, card_id, MIN(id) keep_id FROM decksideslot
    WHERE card_id IN (1,11,14,17,20,23,24,25,26,27,29,30,34,35,39,42,48,50,53,57,59,60,61,66,73,79,89,94,99,100,101,104,109,112,121,125,126,127,130,131,132,134,135,142,149,154,162,163,165,177,178,179,183,184,185,187,188,190,196,197,198,199,200,203,204,213,214,219,230,243,245,256,258,266,267,268,269,270,272,274,275,280,281,282,285,290,291,292,300,301,303,305,308,312,313,320,322,324,327,328,329,330,333,334,338,340,341,342,344,345,349,353,364,422,452,453,454,455,456,458,460,462,463,464,477,489,510,514,516,525,526,540,549,552,579,587,593,597,610,624,625,636,639,641,643,675,678,682,685,689,711,724,730,907,938,950,951,952,961,962,963,966,969,970,980,1067,1069,1076,1094) GROUP BY deck_id, card_id HAVING COUNT(*) > 1
  ) d ON s.deck_id = d.cont AND s.card_id = d.card_id AND s.id <> d.keep_id;
UPDATE decklistsideslot s JOIN (
    SELECT MIN(id) keep_id, SUM(quantity) tq FROM decklistsideslot
    WHERE card_id IN (1,11,14,17,20,23,24,25,26,27,29,30,34,35,39,42,48,50,53,57,59,60,61,66,73,79,89,94,99,100,101,104,109,112,121,125,126,127,130,131,132,134,135,142,149,154,162,163,165,177,178,179,183,184,185,187,188,190,196,197,198,199,200,203,204,213,214,219,230,243,245,256,258,266,267,268,269,270,272,274,275,280,281,282,285,290,291,292,300,301,303,305,308,312,313,320,322,324,327,328,329,330,333,334,338,340,341,342,344,345,349,353,364,422,452,453,454,455,456,458,460,462,463,464,477,489,510,514,516,525,526,540,549,552,579,587,593,597,610,624,625,636,639,641,643,675,678,682,685,689,711,724,730,907,938,950,951,952,961,962,963,966,969,970,980,1067,1069,1076,1094) GROUP BY decklist_id, card_id HAVING COUNT(*) > 1
  ) d ON s.id = d.keep_id SET s.quantity = d.tq;
DELETE s FROM decklistsideslot s JOIN (
    SELECT decklist_id AS cont, card_id, MIN(id) keep_id FROM decklistsideslot
    WHERE card_id IN (1,11,14,17,20,23,24,25,26,27,29,30,34,35,39,42,48,50,53,57,59,60,61,66,73,79,89,94,99,100,101,104,109,112,121,125,126,127,130,131,132,134,135,142,149,154,162,163,165,177,178,179,183,184,185,187,188,190,196,197,198,199,200,203,204,213,214,219,230,243,245,256,258,266,267,268,269,270,272,274,275,280,281,282,285,290,291,292,300,301,303,305,308,312,313,320,322,324,327,328,329,330,333,334,338,340,341,342,344,345,349,353,364,422,452,453,454,455,456,458,460,462,463,464,477,489,510,514,516,525,526,540,549,552,579,587,593,597,610,624,625,636,639,641,643,675,678,682,685,689,711,724,730,907,938,950,951,952,961,962,963,966,969,970,980,1067,1069,1076,1094) GROUP BY decklist_id, card_id HAVING COUNT(*) > 1
  ) d ON s.decklist_id = d.cont AND s.card_id = d.card_id AND s.id <> d.keep_id;

-- 7) Delete the now-merged loser card rows.
DELETE c FROM card c JOIN _merge_map m ON c.id = m.loser_id;

-- 8) Flag the repackaged products (collection page groups them separately).
UPDATE pack SET is_repackaged = 1 WHERE id IN (61,85,98,99,100,101);

-- 9) Correct the placeholder release dates on the repackaged packs.
--    The original data had fake 2011 dates; actual release dates are:
--    Two-Player Limited Edition Starter: July 2017
--    Revised Core Campaign-Only + 4 Starter Decks: November 2022
UPDATE pack SET date_release = '2017-07-06' WHERE id = 61;
UPDATE pack SET date_release = '2022-11-04' WHERE id = 85;
UPDATE pack SET date_release = '2022-11-04' WHERE id = 98;
UPDATE pack SET date_release = '2022-11-04' WHERE id = 99;
UPDATE pack SET date_release = '2022-11-04' WHERE id = 100;
UPDATE pack SET date_release = '2022-11-04' WHERE id = 101;

DROP TEMPORARY TABLE _merge_map;
COMMIT;
