# these routes are available to anybody
AppBundle_api_public:
    resource: "@AppBundle/Resources/config/routing/api/routing_api_public.yml"
    prefix: /public

# these routes are available to logged users
AppBundle_api_private:
    resource: "@AppBundle/Resources/config/routing/api/routing_api_private.yml"
    prefix: /private

api_intro:
    path: /
    defaults:
        _controller: AppBundle:Default:apiIntro
