
collection_custom_pack_new:
    path: /custom-pack/new
    methods: [GET]
    defaults:
        _controller: AppBundle:CustomPack:newForm

collection_custom_pack_save:
    path: /custom-pack/save
    methods: [POST]
    defaults:
        _controller: AppBundle:CustomPack:save

collection_custom_pack_edit:
    path: /custom-pack/{id}/edit
    methods: [GET]
    defaults:
        _controller: AppBundle:CustomPack:editForm
    requirements:
        id: \d+

collection_custom_pack_update:
    path: /custom-pack/{id}/update
    methods: [POST]
    defaults:
        _controller: AppBundle:CustomPack:update
    requirements:
        id: \d+

collection_custom_pack_delete:
    path: /custom-pack/{id}/delete
    methods: [POST]
    defaults:
        _controller: AppBundle:CustomPack:delete
    requirements:
        id: \d+

collection_custom_pack_toggle:
    path: /custom-pack/{id}/toggle
    methods: [POST]
    defaults:
        _controller: AppBundle:CustomPack:toggle
    requirements:
        id: \d+

collection_packs:
    path: /packs
    methods: [GET]
    defaults:
        _controller: AppBundle:Collection:packs

collection_save_packs:
    path: /packs/save
    methods: [POST]
    defaults:
        _controller: AppBundle:Collection:savePacks

collection_save_art:
    path: /art/save
    methods: [POST]
    defaults:
        _controller: AppBundle:Collection:saveArtPreference
    options:
        expose: true
