AppBundle\Entity\Encounter:
    type: entity
    table: encounter
    manyToOne:
        pack:
            targetEntity: Pack
            joinColumn:
                name: pack_id
                referencedColumnName: id
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        code:
            type: string
            length: 255
            nullable: false
        name:
            type: string
            length: 1024
            nullable: false
        dateCreation:
            type: datetime
            nullable: false
            column: date_creation
            gedmo:
                timestampable:
                    on: create
        dateUpdate:
            type: datetime
            nullable: false
            column: date_update
            gedmo:
                timestampable:
                    on: update
    uniqueConstraints:
        encounter_code_idx:
            columns: [ code ]