admin_pack:
    path:  /
    defaults: { _controller: 'App\Controller\PackController::indexAction' }

admin_pack_show:
    path:  /{id}/show
    defaults: { _controller: 'App\Controller\PackController::showAction' }

admin_pack_new:
    path:  /new
    defaults: { _controller: 'App\Controller\PackController::newAction' }

admin_pack_create:
    path:  /create
    defaults: { _controller: 'App\Controller\PackController::createAction' }
    methods: [ post ]

admin_pack_edit:
    path:  /{id}/edit
    defaults: { _controller: 'App\Controller\PackController::editAction' }

admin_pack_update:
    path:  /{id}/update
    defaults: { _controller: 'App\Controller\PackController::updateAction' }
    methods: [ post, put ]

admin_pack_delete:
    path:  /{id}/delete
    defaults: { _controller: 'App\Controller\PackController::deleteAction' }
    methods: [ post, delete ]
