csv_upload_form:
    path: /upload
    methods: [GET]
    defaults:
        _controller: App\Controller\CSVController::uploadFormAction

csv_upload_process:
    path: /upload
    methods: [POST]
    defaults:
        _controller: App\Controller\CSVController::uploadProcessAction
