admin_card_printing:
    path:  /
    defaults: { _controller: 'App\Controller\CardPrintingController::indexAction' }

admin_card_printing_show:
    path:  /{id}/show
    defaults: { _controller: 'App\Controller\CardPrintingController::showAction' }

admin_card_printing_new:
    path:  /new
    defaults: { _controller: 'App\Controller\CardPrintingController::newAction' }

admin_card_printing_create:
    path:  /create
    defaults: { _controller: 'App\Controller\CardPrintingController::createAction' }
    methods: [ post ]

admin_card_printing_edit:
    path:  /{id}/edit
    defaults: { _controller: 'App\Controller\CardPrintingController::editAction' }

admin_card_printing_update:
    path:  /{id}/update
    defaults: { _controller: 'App\Controller\CardPrintingController::updateAction' }
    methods: [ post, put ]

admin_card_printing_delete:
    path:  /{id}/delete
    defaults: { _controller: 'App\Controller\CardPrintingController::deleteAction' }
    methods: [ post, delete ]
