admin_cycle:
    path:  /
    defaults: { _controller: 'App\Controller\CycleController::indexAction' }

admin_cycle_show:
    path:  /{id}/show
    defaults: { _controller: 'App\Controller\CycleController::showAction' }

admin_cycle_new:
    path:  /new
    defaults: { _controller: 'App\Controller\CycleController::newAction' }

admin_cycle_create:
    path:  /create
    defaults: { _controller: 'App\Controller\CycleController::createAction' }
    methods: [ post ]

admin_cycle_edit:
    path:  /{id}/edit
    defaults: { _controller: 'App\Controller\CycleController::editAction' }

admin_cycle_update:
    path:  /{id}/update
    defaults: { _controller: 'App\Controller\CycleController::updateAction' }
    methods: [ post, put ]

admin_cycle_delete:
    path:  /{id}/delete
    defaults: { _controller: 'App\Controller\CycleController::deleteAction' }
    methods: [ post, delete ]
