admin_scenario:
    path:  /
    defaults: { _controller: 'App\Controller\ScenarioController::indexAction' }

admin_scenario_show:
    path:  /{id}/show
    defaults: { _controller: 'App\Controller\ScenarioController::showAction' }

admin_scenario_new:
    path:  /new
    defaults: { _controller: 'App\Controller\ScenarioController::newAction' }

admin_scenario_create:
    path:  /create
    defaults: { _controller: 'App\Controller\ScenarioController::createAction' }
    methods: [ post ]

admin_scenario_edit:
    path:  /{id}/edit
    defaults: { _controller: 'App\Controller\ScenarioController::editAction' }

admin_scenario_update:
    path:  /{id}/update
    defaults: { _controller: 'App\Controller\ScenarioController::updateAction' }
    methods: [ post, put ]

admin_scenario_delete:
    path:  /{id}/delete
    defaults: { _controller: 'App\Controller\ScenarioController::deleteAction' }
    methods: [ post, delete ]
