App\Entity\Deckslot:
    type: entity
    table: deckslot
    manyToOne:
        deck:
            targetEntity: Deck
            inversedBy: slots
            joinColumn:
                name: deck_id
                referencedColumnName: id
                nullable: false
        card:
            targetEntity: Card
            joinColumn:
                name: card_id
                referencedColumnName: id
                nullable: false
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        quantity:
            type: smallint
